name: Compile + Deploy to GitHub pages
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node 18
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    - run: sudo apt -y install golang-go
    - run: npm ci

    - name: Compile WebAssembly
      run: |
        cp "$(go env GOROOT)/misc/wasm/wasm_exec.js" ./public/
        cd GoKernel
        GOOS=js GOARCH=wasm go build -o ../public/main.wasm
        cd -

    - run: npm run build

    - name: Init new repo in dist folder and commit generated files
      run: |
        cd ./build
        git init
        git add -A
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m 'deploy'
        git branch -m main

    - name: Force push to destination branch
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh_pages
        force: true
        directory: ./build
